name: vercel_edge
description: Write and deploy Dart functions to the Vercel Edge network.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/cloudflare_workers
version: 0.0.1-dev.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.1-dev.1
  js_bindings: ^0.1.0
  js: ^0.6.5
  path: ^1.8.3
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
