name: vercel_edge_shelf_example
description: An example of using Vercel Edge with Shelf.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.2
  vercel_edge: ^0.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3

