name: supabase_edge_functions_example
description: A Supaabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.6+1
  edge_http_client: ^0.0.1+2
  supabase: ^1.6.3
  supabase_functions: ^0.0.2+2
  yet_another_json_isolate: ^1.0.2

dev_dependencies:
  lints: ^2.0.1