name: supabase_functions_example
description: A Supabase Edge Function written in Dart.
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.6+1
  supabase_functions: ^0.0.2+3