name: edge_runtime
description: Runtime APIs for running Dart on Edge function environments.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/edge_runtime
version: 0.0.4+2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  js: ^0.6.5
  js_bindings: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http: ^0.13.0
