name: deno_deploy
description: Runtime APIs for running Dart Edge on Deno Deploy environments.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/deno_deploy
version: 0.0.1-dev.6

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  js: ^0.6.5
  js_bindings: ^0.1.0
  edge_runtime: ^0.0.4+2