name: edge
description: Run Dart code on Edge functions, supporting Vercel and Cloudflare Workers.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/edge
version: 0.0.7

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.3.2
  path: ^1.8.3
  hotreloader: ^3.0.5
  toml: ^0.13.1
  glob: ^2.1.1
  mason: ^0.1.0-dev.41
  watcher: ^1.0.2
  prompts: ^2.0.0
  mason_logger: ^0.2.5
  yaml: ^3.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

executables:
  edge:
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
