name: cloudflare_workers_example
description: An example Cloudflare Worker written in Dart.
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloudflare_workers: 0.0.1-dev.1
  edge: ^0.0.2